[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "AH4kBFYyJiR1aFkCuJ6zC4PyqiUxsR2hJTFVdfqoPZYn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
